# Generated by Django 3.2.7 on 2021-09-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
