# Generated by Django 3.2.7 on 2021-09-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210924_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available To Borrow'), ('borrowed', 'Borrowed By Someone Else')], default='available', max_length=15),
        ),
    ]
