# Generated by Django 3.2.7 on 2021-09-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('t', 'Available'), ('f', 'Borrowed')], default='t', max_length=15),
        ),
    ]
