# Generated by Django 3.2.7 on 2021-09-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=7),
        ),
    ]
