# Generated by Django 3.2.7 on 2021-09-27 01:55

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50, verbose_name=django.forms.widgets.PasswordInput),
        ),
    ]
